version: "3.7"

services:

  webapp:
    container_name: indicators_app
    image: kulas971/django-indicators_app
    tty: true
    build:
      context: .
    restart: on-failure:5
    ports:
      - "8000:8000"
    volumes:
      - ./indicatorsproject:/indicatorsproject
    command: >
      sh -c "python manage.py makemigrations --noinput &&
       python manage.py migrate &&
       python manage.py runserver 0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
      container_name: indicators_db
      image: kulas971/django-indicators_db
      ports:
        - '5432'
      environment:
        - POSTGRES_DB=indicators_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrespassword
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
