version: "3.7"

services:
  indicatorsproject:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./indicatorsproject:/indicatorsproject
    command: >
      sh -c "python estate_pro/manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1

db:
  image: indicators_db
